"""Complaint PDF generator using reportlab.

Generates bilingual (EN/HI) FIR/complaint PDFs from RecoveryCase data.
"""

import io
import logging
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

logger = logging.getLogger(__name__)


def generate_complaint_pdf(
    case_id: str,
    fraud_type: str,
    amount_lost: float,
    incident_date: str,
    victim_name: str = "________________",
    victim_phone: str = "________________",
    bank_name: str = "________________",
    scammer_info: str = "Unknown",
    steps: Optional[list] = None,
) -> bytes:
    """Generate a complaint PDF for filing with cybercrime authorities.

    Returns:
        Raw PDF bytes.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width / 2, height - 30 * mm, "CYBER CRIME COMPLAINT")
    c.setFont("Helvetica", 10)
    c.drawCentredString(width / 2, height - 38 * mm, "TrustShield Fraud Detection Platform")

    # Case reference
    y = height - 55 * mm
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20 * mm, y, f"Case Reference: {case_id[:8].upper()}")
    c.setFont("Helvetica", 10)
    c.drawString(20 * mm, y - 5 * mm, f"Date: {incident_date}")
    c.drawString(120 * mm, y, f"Fraud Type: {fraud_type.replace('_', ' ').title()}")

    # Complainant details
    y -= 20 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "1. Complainant Details")
    c.setFont("Helvetica", 10)
    y -= 8 * mm
    c.drawString(25 * mm, y, f"Name: {victim_name}")
    y -= 6 * mm
    c.drawString(25 * mm, y, f"Phone: {victim_phone}")
    y -= 6 * mm
    c.drawString(25 * mm, y, f"Bank: {bank_name}")

    # Incident details
    y -= 12 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "2. Incident Details")
    c.setFont("Helvetica", 10)
    y -= 8 * mm
    c.drawString(25 * mm, y, f"Fraud Type: {fraud_type.replace('_', ' ').title()}")
    y -= 6 * mm
    c.drawString(25 * mm, y, f"Amount Lost: Rs. {amount_lost:,.0f}")
    y -= 6 * mm
    c.drawString(25 * mm, y, f"Date of Incident: {incident_date}")
    y -= 6 * mm
    c.drawString(25 * mm, y, f"Scammer Details: {scammer_info}")

    # Steps taken
    if steps:
        y -= 12 * mm
        c.setFont("Helvetica-Bold", 12)
        c.drawString(20 * mm, y, "3. Steps Taken")
        c.setFont("Helvetica", 10)
        y -= 8 * mm
        for i, step in enumerate(steps[:6], 1):
            status = "[X]" if step.get("completed") else "[ ]"
            c.drawString(25 * mm, y, f"{status} {step.get('title', f'Step {i}')}")
            y -= 6 * mm

    # Helpline numbers
    y -= 12 * mm
    c.setFont("Helvetica-Bold", 12)
    c.drawString(20 * mm, y, "4. Important Helpline Numbers")
    c.setFont("Helvetica", 10)
    y -= 8 * mm
    helplines = [
        ("National Cybercrime Helpline", "1930"),
        ("Cybercrime Portal", "cybercrime.gov.in"),
        ("NPCI UPI Dispute", "od@npci.org.in"),
        ("RBI Ombudsman", "14448"),
    ]
    for name, number in helplines:
        c.drawString(25 * mm, y, f"{name}: {number}")
        y -= 6 * mm

    # Declaration
    y -= 12 * mm
    c.setFont("Helvetica-Bold", 11)
    c.drawString(20 * mm, y, "Declaration")
    c.setFont("Helvetica", 9)
    y -= 6 * mm
    c.drawString(20 * mm, y, "I hereby declare that the above information is true and correct to the best of my knowledge.")
    y -= 6 * mm
    c.drawString(20 * mm, y, "I understand that filing a false complaint is punishable under Indian law.")

    # Signature
    y -= 15 * mm
    c.drawString(20 * mm, y, "Signature: _______________________")
    c.drawString(120 * mm, y, "Date: _______________________")

    # Footer
    c.setFont("Helvetica", 8)
    c.drawCentredString(width / 2, 15 * mm, "Generated by TrustShield | For official use only")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer.getvalue()
